WebUI/AdsGarden.YouVolume/Controllers/CategoryController.cs
namespace AdsGarden.YouVolume.Controllers
{
    using AdsGarden.Data;
    using AdsGarden.Model;
    using AdsGarden.YouVolume.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class CategoryController : Controller
    {
        CategoryData _categoryData;
        ContentData _contentData;

        public CategoryController()
        {
            _categoryData = new CategoryData();
            _contentData = new ContentData();
        }

        public ActionResult Index(string slug, int page = 1)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Error", "Home", new { e = "no-slug" });

            var category = _categoryData.GetBy(x => x.Slug == slug).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Error", "Home", new { e = "category-not-found" });

            int _pageSize = 15;

            var contents = _contentData.GetByPage(x => x.CategoryId == category.Id && x.SiteId == category.SiteId && x.PublishDate <= DateTime.Now,page, _pageSize, "Id",true);
            var count = _contentData.GetCount(x => x.CategoryId == category.Id && x.SiteId == category.SiteId && x.PublishDate <= DateTime.Now);

            var model = new CategoryDetailViewModel()
            {
                Contents = contents,
                Category = category,
                TotalPageCount = (int)(count / _pageSize),
                CurrentPage = page
            };

            return View(model);
        }
    }
}

WebUI/AdsGarden.YouVolume/Controllers/PageController.cs
namespace AdsGarden.YouVolume.Controllers
{
    using AdsGarden.Data;
    using AdsGarden.YouVolume.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class PageController : Controller
    {
        PageData _pageData;

        public PageController()
        {
            _pageData = new PageData();
        }

        public ActionResult Index(string slug)
        {
            if(string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { q = "page-no-slug" });

            var page = _pageData.GetBy(x => x.Slug == slug).FirstOrDefault();
            if(page == null)
                return RedirectToAction("Index", "Home", new { q = "page-no-slug" });

            return View(page);
        }
    }
}

WebUI/AdsGarden.YouVolume/Views/Shared/_CmdLayout.cshtml
@{
    Layout = null;
    
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="~/_admin/css/icomoon.css" rel="stylesheet" type="text/css">
    <link href="~/_admin/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/_admin/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
    <link href="~/_admin/css/layout.min.css" rel="stylesheet" type="text/css">
    <link href="~/_admin/css/components.min.css" rel="stylesheet" type="text/css">
    <link href="~/_admin/css/colors.min.css" rel="stylesheet" type="text/css">
    <link href="~/_admin/css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="navbar navbar-expand-md navbar-dark fixed-top">
        <div class="navbar-brand">
            <a href="@Url.Action("Index","Home")" class="d-inline-block">
                <img src="~/_vendor/img/aboutme.jpg" alt="">
            </a>
        </div>

        <div class="d-md-none pr-4">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
                <i class="icon-paragraph-justify3"></i>
            </button>
            <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
                <i class="icon-tree5"></i>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-mobile">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="/Cmd/Index" class="navbar-nav-link">Ana Sayfa</a></li>
                <li class="nav-item"><a href="@Url.Action("Content","Cmd", new { page = 1 })" class="navbar-nav-link">Makaleler</a></li>
                <li class="nav-item"><a href="@Url.Action("Settings","Cmd")" class="navbar-nav-link">Ayarlar</a></li>
                @*<li class="nav-item dropdown">
                    <a class="navbar-nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" data-hover="dropdown">
                        Pomodoro
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("Index","HangService")"><i class="icon-arrow-right5"></i> Günlük Pomodorolar</a>
                        <a class="dropdown-item" href="@Url.Action("Index","DailyMission")"><i class="icon-arrow-right5"></i> Pomodorolar</a>
                    </div>
                </li>*@
            </ul>
        </div>
    </div>

    <div class="page-content">
        <div class="sidebar bg-white text-dark sidebar-main sidebar-fixed sidebar-expand-md">

            <div class="sidebar-mobile-toggler text-center">
                <a href="#" class="sidebar-mobile-main-toggle">
                    <i class="icon-arrow-left8"></i>
                </a>
                Pomodorolar
                <a href="#" class="sidebar-mobile-expand">
                    <i class="icon-screen-full"></i>
                    <i class="icon-screen-normal"></i>
                </a>
            </div>
            <div class="sidebar-content">
                <div class="card card-sidebar-mobile">
                    <ul class="nav nav-sidebar" data-nav-type="accordion">
                        <li class="nav-item pt-0">
                            <div class="card bg-white side-card">
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="content-wrapper">
            @RenderBody()
        </div>
    </div>

    <script src="~/_admin/js/jquery.min.js"></script>
    <script src="~/_admin/js/bootstrap.bundle.min.js"></script>
    <script src="~/_admin/js/blockui.min.js"></script>
    <script src="~/_admin/js/d3.min.js"></script>
    <script src="~/_admin/js/d3_tooltip.js"></script>
    <script src="~/_admin/js/switchery.min.js"></script>
    <script src="~/_admin/js/bootstrap_multiselect.js"></script>
    <script src="~/_admin/js/moment.min.js"></script>
    <script src="~/_admin/js/daterangepicker.js"></script>
    <script src="~/_admin/js/daterangepicker.tr.js"></script>
    <script src="~/_admin/js/app.js"></script>
    <script src="~/_admin/js/pnotify.min.js"></script>
    <script src="~/_admin/js/select2.min.js"></script>

    <script src="~/_admin/js/interactions.min.js"></script>
    <script src="~/_admin/js/select2.min.js"></script>
    <script src="~/_admin/js/form_select2.js"></script>

    <script src="~/_admin/js/form_layouts.js"></script>

    <script>
        $(document).ready(function () {
            function callDatePicker(params) {
                return;
            }
            $.datepicker = new callDatePicker(null);
        });
    </script>

    @RenderSection("scripts", required: false)
    @RenderSection("styles", required: false)
</body>
</html>

WebUI/AdsGarden.YouVolume/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="@CacheHelper.Settings.Sitename">
    @if (ViewBag.Keywords != null)
    {
        <meta name="keywords" content="@ViewBag.Keywords">
    }
    @if (!string.IsNullOrEmpty(ViewBag.Description))
    {
        <meta name="description" content="@ViewBag.Description">
    }
    @if (!string.IsNullOrEmpty(ViewBag.Title))
    {
        <title>@ViewBag.Title</title>
    }
    @if (!string.IsNullOrEmpty(ViewBag.Canonical))
    {
        <link rel="canonical" href="@ViewBag.Canonical" />
    }
    @if (!string.IsNullOrEmpty(ViewBag.AmpCanonical))
    {
        <link rel="amphtml" href="@ViewBag.AmpCanonical" />
    }
    @if (!string.IsNullOrEmpty(ViewBag.Robots))
    {
        <meta name="robots" content="@ViewBag.Robots" />
    }
    <!-- Include All CSS -->
    <link rel="stylesheet" type="text/css" href="~/_vendor/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/_vendor/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/_vendor/css/owl.carousel.css" />
    <link rel="stylesheet" type="text/css" href="~/_vendor/css/owl.theme.css" />
    <link rel="stylesheet" type="text/css" href="~/_vendor/css/preset.css" />
    <link rel="stylesheet" type="text/css" href="~/_vendor/css/jquery.mCustomScrollbar.css" />
    <link rel="stylesheet" type="text/css" href="~/_vendor/css/style.css" />
    <link rel="stylesheet" type="text/css" href="~/_vendor/css/responsive.css" />
    <!-- End Include All CSS -->
    <!-- Favicon Icon -->
    <link rel="icon" type="image/png" href="@CacheHelper.Settings.LogoPath">
    <!-- Favicon Icon -->

    @if (!string.IsNullOrEmpty(CacheHelper.Settings.AdsenseVerifiedCode))
    {
        @Html.Raw(CacheHelper.Settings.AdsenseVerifiedCode)
    }

</head>
<body class="animat">
    <div id="page">
        <div class="leftMenu">
            <div class="leftmenuHead">
                <div class="logoleft pull-left">
                    <a href="@Url.Action("Index","Home")">
                        <img src="@CacheHelper.Settings.LogoPath"
                             alt="World in best of gardens"
                             title="World in best of gardens" />
                    </a>
                </div>
                <a href="#" class="leftclose pull-right">x</a>
                <div class="clearfix"></div>
            </div>
            <div class="leftmenuScroll">
                <nav class="leftmainnav">
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><a href="@Url.Action("Index","Page", new { slug = "about" })">About</a></li>
                        <li class="has-menu-items">
                            <a href="#">categories</a>
                            <ul class="sub-menu">
                                @foreach (var item in CacheHelper.Categories)
                                {
                                    <li><a href="@Url.Action("Index","Category", new { slug = item.Slug })" title="@item.MetaTitle">@item.Title</a></li>
                                }
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Index","Page", new { slug = "contact" })">Contact</a></li>
                    </ul>
                </nav>
            </div>
            <div class="socialleft">
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Facebook))
                {
                    <a href="@CacheHelper.Settings.Facebook"><i class="fa fa-facebook"></i></a>
                }
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Twitter))
                {
                    <a href="@CacheHelper.Settings.Twitter"><i class="fa fa-twitter"></i></a>
                }
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Youtube))
                {
                    <a href="@CacheHelper.Settings.Youtube"><i class="fa fa-youtube"></i></a>
                }
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Instagram))
                {
                    <a href="@CacheHelper.Settings.Instagram"><i class="fa fa-instagram"></i></a>
                }
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Pinterest))
                {
                    <a href="@CacheHelper.Settings.Pinterest"><i class="fa fa-pinterest"></i></a>
                }
            </div>
        </div>
        <section class="headerTop">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-xs-2">
                    </div>
                    <div class="col-lg-4 col-xs-8 text-center">
                        <div class="logo">
                            <a href="@Url.Action("Index","Home")" title="@CacheHelper.Settings.Sitename Homepage"><img src="@CacheHelper.Settings.LogoPath" alt="World in best of gardens" title="World in best of gardens"></a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-xs-2 text-right">
                        <div class="search">
                            <a href="#">
                                <i class="fa fa-search"></i>
                            </a>
                            <form action="#" method="post" class="searchForm">
                                <input type="search" name="search" placeholder="Search...">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <header class="header">
            <div class="container">
                <div class="headerIn">
                    <div class="row">
                        <div class="col-lg-8 col-sm-9 col-xs-12 pull-left noPaddingRight">
                            <nav class="mainNav">
                                <div class="menuBar hidden-lg hidden-md">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div>
                                <ul>
                                    <li class="has-menu-items"><a href="@Url.Action("Index","Home")">Home</a></li>
                                    <li class="has-menu-items"><a href="@Url.Action("Index","Page", new { slug = "about" })">About</a></li>
                                    <li class="has-menu-items">
                                        <a href="javascript:void('0')">categories</a>
                                        <ul class="sub-menu">
                                            @foreach (var item in CacheHelper.Categories)
                                            {
                                                <li><a href="@Url.Action("Index","Category", new { slug = item.Slug })">@item.Title</a></li>
                                            }
                                        </ul>
                                    </li>
                                    <li><a href="@Url.Action("Index","Page", new { slug = "contact" })">Contact</a></li>
                                </ul>
                            </nav>
                        </div>
                        <div class="col-lg-4 col-sm-3 col-xs-8 pull-right text-right">
                            <div class="socialHeader">
                                <a href="@CacheHelper.Settings.Facebook"><i class="fa fa-facebook"></i></a>
                                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Twitter))
                                {
                                    <a href="@CacheHelper.Settings.Twitter"><i class="fa fa-twitter"></i></a>
                                }
                                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Youtube))
                                {
                                    <a href="@CacheHelper.Settings.Youtube"><i class="fa fa-youtube"></i></a>
                                }
                                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Instagram))
                                {
                                    <a href="@CacheHelper.Settings.Instagram"><i class="fa fa-instagram"></i></a>
                                }
                                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Pinterest))
                                {
                                    <a href="@CacheHelper.Settings.Pinterest"><i class="fa fa-pinterest"></i></a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section class="mainContent">
            <div class="container">
                <div class="row">
                    @RenderBody()
                    @Html.Partial("_Sidebar")
                </div>
            </div>
        </section>

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3 text-center">
                        <div class="footLogo">
                            <a href="@Url.Action("Index","Home")">
                                <img src="@CacheHelper.Settings.LogoPath"
                                     alt="World in best of gardens"
                                     title="World in best of gardens" />
                            </a>
                        </div>
                        <p class="copyrightText">World in best of gardens <br /><span>Copyright © 2016 @CacheHelper.Settings.Sitename. All Right Reserved</span></p>
                        <div class="footSocial">
                            @if (!string.IsNullOrEmpty(CacheHelper.Settings.Facebook))
                            {
                                <a href="@CacheHelper.Settings.Facebook"><i class="fa fa-facebook"></i></a>
                            }
                            @if (!string.IsNullOrEmpty(CacheHelper.Settings.Twitter))
                            {
                                <a href="@CacheHelper.Settings.Twitter"><i class="fa fa-twitter"></i></a>
                            }
                            @if (!string.IsNullOrEmpty(CacheHelper.Settings.Youtube))
                            {
                                <a href="@CacheHelper.Settings.Youtube"><i class="fa fa-youtube"></i></a>
                            }
                            @if (!string.IsNullOrEmpty(CacheHelper.Settings.Instagram))
                            {
                                <a href="@CacheHelper.Settings.Instagram"><i class="fa fa-instagram"></i></a>
                            }
                            @if (!string.IsNullOrEmpty(CacheHelper.Settings.Pinterest))
                            {
                                <a href="@CacheHelper.Settings.Pinterest"><i class="fa fa-pinterest"></i></a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <!-- Include All JS -->
    <script type="text/javascript" src="~/_vendor/js/jquery.js"></script>
    <script type="text/javascript" src="~/_vendor/js/bootstrap.js"></script>
    <script type="text/javascript" src="~/_vendor/js/owl.carousel.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script type="text/javascript" src="~/_vendor/js/gmaps.js"></script>
    <script type="text/javascript" src="~/_vendor/js/jquery.mCustomScrollbar.js"></script>
    <script type="text/javascript" src="~/_vendor/js/theme.js"></script>

    <script>
        $(".fa-search").click(function () {
            var form = $(".searchForm");
            var search = $("input[name='search']").val();
            if (form[0].attributes.length > 3) {
                if (form[0].attributes[3].value == "display: block;") {
                    if (search.length <= 0) {
                        alert("search text empty");
                    }
                }
            }
            if (search.length <= 0) {
                form.css("display", "block");
            }
        });
    </script>

    @if (!Request.IsLocal)
    {
        @Html.Raw(string.IsNullOrEmpty(CacheHelper.Settings.Analytics) ? "" : CacheHelper.Settings.Analytics)
    }

</body>
</html>

WebUI/AdsGarden.YouVolume/Views/Shared/_Sidebar.cshtml
<div class="col-lg-4 col-sm-5">
    <div class="sidebarBlog">
        @*<aside class="widget">
                <h3 class="widgetTitle">ABOUT ME</h3>
                <div class="aboutMe">
                    <img src="~/_vendor/img/aboutme.jpg" alt="">
                    <div class="aboutdec">
                        <h4>Hernandez Higuan</h4>
                        <p>Doing business like this takes much more effort than doing your own business at home, and on top of that there's the curse of travelling, worries about making train connections, bad and irregular food.</p>
                    </div>
                </div>
            </aside>*@
        <aside class="widget">
            <div class="followMe">
                <h2 class="widgetTitle">follow me</h2>
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Facebook))
                {
                    <a href="@CacheHelper.Settings.Facebook"><i class="fa fa-facebook"></i></a>
                }
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Twitter))
                {
                    <a href="@CacheHelper.Settings.Twitter"><i class="fa fa-twitter"></i></a>
                }
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Youtube))
                {
                    <a href="@CacheHelper.Settings.Youtube"><i class="fa fa-youtube"></i></a>
                }
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Instagram))
                {
                    <a href="@CacheHelper.Settings.Instagram"><i class="fa fa-instagram"></i></a>
                }
                @if (!string.IsNullOrEmpty(CacheHelper.Settings.Pinterest))
                {
                    <a href="@CacheHelper.Settings.Pinterest"><i class="fa fa-pinterest"></i></a>
                }
            </div>
        </aside>
        @*<aside class="widget">
                <div class="banner">
                    <img src="~/_vendor/img/b1.jpg" alt="">
                    <div class="bannerCont">
                        <h2>dhaka</h2>
                        <p>WORDPRESS THEME FOR BLOGGERS</p>
                    </div>
                </div>
            </aside>*@
        <aside class="widget">
            <h3 class="widgetTitle">RECENT POSTS</h3>
            <div class="recentPost">
                @foreach (var item in CacheHelper.EditorPick)
                {
                    <div class="singleRecpost">
                        <img src="@item.ImagePath"
                             alt="@item.MetaDescription"
                             title="@item.MetaTitle">
                        <h2 class="recTitle">
                            <a href="@Url.Action("Index","Content", new { slug = item.Slug })">@item.Title</a>
                        </h2>
                    </div>
                }
            </div>
        </aside>
        <aside class="widget emailSub">
            <h3 class="widgetTitle">subcribe</h3>
            <p>Subscribe out mail list</p>
            <form action="#" method="post" class="subForm" id="subscriptionsforms">
                <input type="email" placeholder="Your email address" id="sub_email">
                <button type="submit" id="subs_submit">sign up</button>
            </form>
        </aside>
        <aside class="widget emailSub">
            <h3 class="widgetTitle">CATEGORIES</h3>
            <ul>
                @foreach (var item in CacheHelper.Categories)
                {
                    <li><a href="@Url.Action("Index","Category", new { slug = item.Slug })">@item.Title</a></li>
                }
            </ul>
        </aside>
        @*<aside class="widget">
                <div class="flickr">
                    <h2 class="widgetTitle">flickr photo</h2>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                    <a href="#"><img src="~/_vendor/img/1.jpg" alt=""></a>
                </div>
            </aside>*@
    </div>
</div>