WebUI/AdsGarden.YouVolume/Models/CategoryViewModel.cs
namespace AdsGarden.YouVolume.Models
{
    using AdsGarden.Model;
    using System.Collections.Generic;

    public class CategoryViewModel
    {
        public CategoryViewModel()
        {
            CategoryList = new List<Category>();
        }

        public List<Category> CategoryList { get; set; }
    }
}

WebUI/AdsGarden.YouVolume/Controllers/CategoryController.cs
namespace AdsGarden.YouVolume.Controllers
{
    using AdsGarden.Data;
    using AdsGarden.Model;
    using AdsGarden.YouVolume.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class CategoryController : Controller
    {
        CategoryData _categoryData;
        ContentData _contentData;

        public CategoryController()
        {
            _categoryData = new CategoryData();
            _contentData = new ContentData();
        }

        public ActionResult Index(string slug, int page = 1)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Error", "Home", new { e = "no-slug" });

            var category = _categoryData.GetBy(x => x.Slug == slug).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Error", "Home", new { e = "category-not-found" });

            int _pageSize = 15;

            var contents = _contentData.GetByPage(x => x.CategoryId == category.Id && x.SiteId == category.SiteId && x.PublishDate <= DateTime.Now,page, _pageSize, "Id",true);
            var count = _contentData.GetCount(x => x.CategoryId == category.Id && x.SiteId == category.SiteId && x.PublishDate <= DateTime.Now);

            var model = new CategoryDetailViewModel()
            {
                Contents = contents,
                Category = category,
                TotalPageCount = (int)(count / _pageSize),
                CurrentPage = page
            };

            return View(model);
        }
    }
}

WebUI/AdsGarden.YouVolume/Controllers/ContentController.cs
namespace AdsGarden.YouVolume.Controllers
{
    using AdsGarden.Data;
    using AdsGarden.YouVolume.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Mvc;

    public class ContentController : Controller
    {
        ContentData _contentData;
        InfoData _infoData;

        public ContentController()
        {
            _contentData = new ContentData();
            _infoData = new InfoData();
        }

        public ActionResult Index(string slug)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { t = "no-slug" });

            var content = _contentData.GetBy(x => x.Slug == slug && x.IsActive).LastOrDefault();

            if (content == null)
                return View("Index", "Home", new { e = "not-found-content" });

            var info = _infoData.GetBy(x => x.ContentId == content.Id).FirstOrDefault();

            var related = _contentData.GetRandom(x => x.CategoryId == content.CategoryId && x.SiteId == content.SiteId && x.PublishDate <= DateTime.Now, 3);

            var model = new ContentViewModel
            {
                Content = content,
                RelatedContent = related,
                Info = info
            };

            return View(model);
        }

        public ActionResult Amp(string slug)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { t = "no-slug" });

            var content = _contentData.GetBy(x=>x.Slug == slug && x.IsActive).LastOrDefault();

            if (content == null)
                return View("Index", "Home", new { e = "not-found-content" });

            var related = _contentData.GetRandom(x => x.CategoryId == content.CategoryId && x.SiteId == content.SiteId && x.PublishDate <= DateTime.Now, 4);

            var model = new ContentViewModel
            {
                Content = content,
                RelatedContent = related,
            };

            return View(model);
        }
    }
}

WebUI/AdsGarden.YouVolume/Views/Category/Index.cshtml
@model CategoryDetailViewModel
@{
    ViewBag.Title = Model.Category.MetaTitle;
    ViewBag.Description = Model.Category.MetaDescription;
    ViewBag.Keywords = Model.Category.Keywords;
    ViewBag.Canonical = Url.Action("Index", "Category", new { slug = Model.Category.Slug });
    ViewBag.Robots = "index,follow";
}

    <div class="col-lg-8 col-sm-7">
        <div class="row">
            <div class="col-lg-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">@Model.Category.Title</li>
                    </ol>
                </nav>
                <h3 class="widgetTitle">CATEGORY <span>/</span> @Model.Category.Title</h3>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model.Contents)
            {
                <div class="blogHlafWidth">
                    <div class="clearfix"></div>
                    <div class="col-lg-6">
                        <div class="singleBlog hlafWidth">
                            <div class="blogImg">
                                <img src="@item.ImagePath" 
                                     alt="@item.Title"
                                     title="@item.MetaTitle"
                                />
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="blogDec hlafWidthdec">
                            <h2 class="blogtitle">
                                <a href="@Url.Action("Index","Content", new { slug = item.Slug })" title="@item.MetaTitle">@item.Title</a>
                            </h2>
                            <p>@Html.Raw(item.Description.Substring(0,150))<text>...</text></p>
                            <div class="blogMeta">
                                <span><i class="fa fa-user"></i>@item.User.Fullname</span>
                                <span> <i class="fa fa-clock-o"></i>@item.PublishDate.ToString("dd MMMM yyyy")</span>
                                <span><i class="fa fa-comments"></i>@item.Category.Title</span>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>